# $NetBSD$
#

DISTNAME=	Twiggy-0.4.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	http://pypi.python.org/packages/source/T/Twiggy/
EXTRACT_SUFX=	.tar.gz#md5=b0dfbbb7f56342e448af4d22a47a339c

MAINTAINER=	nathan+maint@freeagent.com
HOMEPAGE=	https://twiggy.readthedocs.org/en/latest/
COMMENT=	A Pythonic logger
LICENSE=	mit

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
