# $NetBSD$
#

DISTNAME=	http-parser-0.8.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/h/http-parser/
EXTRACT_SUFX=	.tar.gz#md5=751967e2785c829dffebdc9a511e0eec

MAINTAINER=	nathan+maint@freeagent.com
HOMEPAGE= https://github.com/benoitc/http-parser/
COMMENT=	http request/response parser
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
